name: Java CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Compile
        run: javac src/main/java/com/yerassyl/HelloDevOps.java

      - name: Run
        run: java -cp src/main/java com.yerassyl.HelloDevOps